# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .bare_metal_server import *
from .block_storage import *
from .dns_domain import *
from .dns_record import *
from .firewall_group import *
from .firewall_rule import *
from .get_account import *
from .get_application import *
from .get_backup import *
from .get_bare_metal_plan import *
from .get_bare_metal_server import *
from .get_block_storage import *
from .get_dns_domain import *
from .get_firewall_group import *
from .get_instance import *
from .get_instance_ipv4 import *
from .get_iso_private import *
from .get_iso_public import *
from .get_load_balancer import *
from .get_object_storage import *
from .get_os import *
from .get_plan import *
from .get_private_network import *
from .get_region import *
from .get_reserved_ip import *
from .get_reverse_ipv4 import *
from .get_reverse_ipv6 import *
from .get_snapshot import *
from .get_ssh_key import *
from .get_startup_script import *
from .get_user import *
from .instance import *
from .instance_i_pv4 import *
from .iso_private import *
from .load_balancer import *
from .object_storage import *
from .private_network import *
from .provider import *
from .reserved_ip import *
from .reverse_ipv4 import *
from .reverse_ipv6 import *
from .snapshot import *
from .snapshot_from_url import *
from .ssh_key import *
from .startup_script import *
from .user import *
from ._inputs import *
from . import outputs

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_vultr.config as __config
    config = __config
else:
    config = _utilities.lazy_import('pulumi_vultr.config')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "vultr",
  "mod": "index/bareMetalServer",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/bareMetalServer:BareMetalServer": "BareMetalServer"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/blockStorage",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/blockStorage:BlockStorage": "BlockStorage"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/dnsDomain",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/dnsDomain:DnsDomain": "DnsDomain"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/dnsRecord",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/dnsRecord:DnsRecord": "DnsRecord"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/firewallGroup",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/firewallGroup:FirewallGroup": "FirewallGroup"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/firewallRule",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/firewallRule:FirewallRule": "FirewallRule"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/instance",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/instance:Instance": "Instance"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/instanceIPv4",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/instanceIPv4:InstanceIPv4": "InstanceIPv4"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/isoPrivate",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/isoPrivate:IsoPrivate": "IsoPrivate"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/loadBalancer",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/loadBalancer:LoadBalancer": "LoadBalancer"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/objectStorage",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/objectStorage:ObjectStorage": "ObjectStorage"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/privateNetwork",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/privateNetwork:PrivateNetwork": "PrivateNetwork"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/reservedIP",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/reservedIP:ReservedIP": "ReservedIP"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/reverseIpv4",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/reverseIpv4:ReverseIpv4": "ReverseIpv4"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/reverseIpv6",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/reverseIpv6:ReverseIpv6": "ReverseIpv6"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/snapshot",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/snapshot:Snapshot": "Snapshot"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/snapshotFromUrl",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/snapshotFromUrl:SnapshotFromUrl": "SnapshotFromUrl"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/sshKey",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/sshKey:SshKey": "SshKey"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/startupScript",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/startupScript:StartupScript": "StartupScript"
  }
 },
 {
  "pkg": "vultr",
  "mod": "index/user",
  "fqn": "pulumi_vultr",
  "classes": {
   "vultr:index/user:User": "User"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "vultr",
  "token": "pulumi:providers:vultr",
  "fqn": "pulumi_vultr",
  "class": "Provider"
 }
]
"""
)
