// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package vultr

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Vultr Reverse IPv4.
//
// ## Example Usage
//
// Get the information for an IPv4 reverse DNS record by `reverse`:
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-vultr/sdk/go/vultr"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := vultr.LookupReverseIPv4(ctx, &GetReverseIPv4Args{
// 			Filters: []GetReverseIPv4Filter{
// 				GetReverseIPv4Filter{
// 					Name: "reverse",
// 					Values: []string{
// 						"host.example.com",
// 					},
// 				},
// 			},
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupReverseIPv4(ctx *pulumi.Context, args *LookupReverseIPv4Args, opts ...pulumi.InvokeOption) (*LookupReverseIPv4Result, error) {
	var rv LookupReverseIPv4Result
	err := ctx.Invoke("vultr:index/getReverseIPv4:getReverseIPv4", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getReverseIPv4.
type LookupReverseIPv4Args struct {
	// Query parameters for finding IPv4 reverse DNS records.
	Filters []GetReverseIPv4Filter `pulumi:"filters"`
}

// A collection of values returned by getReverseIPv4.
type LookupReverseIPv4Result struct {
	Filters []GetReverseIPv4Filter `pulumi:"filters"`
	// The gateway IP address.
	Gateway string `pulumi:"gateway"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The ID of the instance the IPv4 reverse DNS record was set for.
	InstanceId string `pulumi:"instanceId"`
	// The IPv4 address in canonical format used in the reverse DNS record.
	Ip string `pulumi:"ip"`
	// The IPv4 netmask in dot-decimal notation.
	Netmask string `pulumi:"netmask"`
	// The hostname used in the IPv4 reverse DNS record.
	Reverse string `pulumi:"reverse"`
}

func LookupReverseIPv4Output(ctx *pulumi.Context, args LookupReverseIPv4OutputArgs, opts ...pulumi.InvokeOption) LookupReverseIPv4ResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupReverseIPv4Result, error) {
			args := v.(LookupReverseIPv4Args)
			r, err := LookupReverseIPv4(ctx, &args, opts...)
			return *r, err
		}).(LookupReverseIPv4ResultOutput)
}

// A collection of arguments for invoking getReverseIPv4.
type LookupReverseIPv4OutputArgs struct {
	// Query parameters for finding IPv4 reverse DNS records.
	Filters GetReverseIPv4FilterArrayInput `pulumi:"filters"`
}

func (LookupReverseIPv4OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupReverseIPv4Args)(nil)).Elem()
}

// A collection of values returned by getReverseIPv4.
type LookupReverseIPv4ResultOutput struct{ *pulumi.OutputState }

func (LookupReverseIPv4ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupReverseIPv4Result)(nil)).Elem()
}

func (o LookupReverseIPv4ResultOutput) ToLookupReverseIPv4ResultOutput() LookupReverseIPv4ResultOutput {
	return o
}

func (o LookupReverseIPv4ResultOutput) ToLookupReverseIPv4ResultOutputWithContext(ctx context.Context) LookupReverseIPv4ResultOutput {
	return o
}

func (o LookupReverseIPv4ResultOutput) Filters() GetReverseIPv4FilterArrayOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) []GetReverseIPv4Filter { return v.Filters }).(GetReverseIPv4FilterArrayOutput)
}

// The gateway IP address.
func (o LookupReverseIPv4ResultOutput) Gateway() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) string { return v.Gateway }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupReverseIPv4ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the instance the IPv4 reverse DNS record was set for.
func (o LookupReverseIPv4ResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) string { return v.InstanceId }).(pulumi.StringOutput)
}

// The IPv4 address in canonical format used in the reverse DNS record.
func (o LookupReverseIPv4ResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) string { return v.Ip }).(pulumi.StringOutput)
}

// The IPv4 netmask in dot-decimal notation.
func (o LookupReverseIPv4ResultOutput) Netmask() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) string { return v.Netmask }).(pulumi.StringOutput)
}

// The hostname used in the IPv4 reverse DNS record.
func (o LookupReverseIPv4ResultOutput) Reverse() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv4Result) string { return v.Reverse }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupReverseIPv4ResultOutput{})
}
