// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package vultr

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
)

// Get information about a Vultr Reverse IPv6.
//
// ## Example Usage
//
// Get the information for an IPv6 reverse DNS record by `reverse`:
//
// ```go
// package main
//
// import (
// 	"github.com/pulumi/pulumi-vultr/sdk/go/vultr"
// 	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
// )
//
// func main() {
// 	pulumi.Run(func(ctx *pulumi.Context) error {
// 		_, err := vultr.LookupReverseIPv6(ctx, &GetReverseIPv6Args{
// 			Filters: []GetReverseIPv6Filter{
// 				GetReverseIPv6Filter{
// 					Name: "reverse",
// 					Values: []string{
// 						"host.example.com",
// 					},
// 				},
// 			},
// 		}, nil)
// 		if err != nil {
// 			return err
// 		}
// 		return nil
// 	})
// }
// ```
func LookupReverseIPv6(ctx *pulumi.Context, args *LookupReverseIPv6Args, opts ...pulumi.InvokeOption) (*LookupReverseIPv6Result, error) {
	var rv LookupReverseIPv6Result
	err := ctx.Invoke("vultr:index/getReverseIPv6:getReverseIPv6", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getReverseIPv6.
type LookupReverseIPv6Args struct {
	// Query parameters for finding IPv6 reverse DNS records.
	Filters []GetReverseIPv6Filter `pulumi:"filters"`
}

// A collection of values returned by getReverseIPv6.
type LookupReverseIPv6Result struct {
	Filters []GetReverseIPv6Filter `pulumi:"filters"`
	// The provider-assigned unique ID for this managed resource.
	Id string `pulumi:"id"`
	// The ID of the instance the IPv6 reverse DNS record was set for.
	InstanceId string `pulumi:"instanceId"`
	// The IPv6 address in canonical format used in the reverse DNS record.
	Ip string `pulumi:"ip"`
	// The hostname used in the IPv6 reverse DNS record.
	Reverse string `pulumi:"reverse"`
}

func LookupReverseIPv6Output(ctx *pulumi.Context, args LookupReverseIPv6OutputArgs, opts ...pulumi.InvokeOption) LookupReverseIPv6ResultOutput {
	return pulumi.ToOutputWithContext(context.Background(), args).
		ApplyT(func(v interface{}) (LookupReverseIPv6Result, error) {
			args := v.(LookupReverseIPv6Args)
			r, err := LookupReverseIPv6(ctx, &args, opts...)
			return *r, err
		}).(LookupReverseIPv6ResultOutput)
}

// A collection of arguments for invoking getReverseIPv6.
type LookupReverseIPv6OutputArgs struct {
	// Query parameters for finding IPv6 reverse DNS records.
	Filters GetReverseIPv6FilterArrayInput `pulumi:"filters"`
}

func (LookupReverseIPv6OutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupReverseIPv6Args)(nil)).Elem()
}

// A collection of values returned by getReverseIPv6.
type LookupReverseIPv6ResultOutput struct{ *pulumi.OutputState }

func (LookupReverseIPv6ResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupReverseIPv6Result)(nil)).Elem()
}

func (o LookupReverseIPv6ResultOutput) ToLookupReverseIPv6ResultOutput() LookupReverseIPv6ResultOutput {
	return o
}

func (o LookupReverseIPv6ResultOutput) ToLookupReverseIPv6ResultOutputWithContext(ctx context.Context) LookupReverseIPv6ResultOutput {
	return o
}

func (o LookupReverseIPv6ResultOutput) Filters() GetReverseIPv6FilterArrayOutput {
	return o.ApplyT(func(v LookupReverseIPv6Result) []GetReverseIPv6Filter { return v.Filters }).(GetReverseIPv6FilterArrayOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupReverseIPv6ResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv6Result) string { return v.Id }).(pulumi.StringOutput)
}

// The ID of the instance the IPv6 reverse DNS record was set for.
func (o LookupReverseIPv6ResultOutput) InstanceId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv6Result) string { return v.InstanceId }).(pulumi.StringOutput)
}

// The IPv6 address in canonical format used in the reverse DNS record.
func (o LookupReverseIPv6ResultOutput) Ip() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv6Result) string { return v.Ip }).(pulumi.StringOutput)
}

// The hostname used in the IPv6 reverse DNS record.
func (o LookupReverseIPv6ResultOutput) Reverse() pulumi.StringOutput {
	return o.ApplyT(func(v LookupReverseIPv6Result) string { return v.Reverse }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupReverseIPv6ResultOutput{})
}
